{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aas-discovery.fullname" . }}
  labels:
    {{- include "aas-discovery.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aas-discovery.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aas-discovery.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /application/application.properties
              name: {{ template "aas-discovery.fullname" $ }}-config
              subPath: application.properties
            - mountPath: /application/rbac-rules.json
              name: {{ template "aas-discovery.fullname" $ }}-rbac-rules
              subPath: rbac-rules.json
      volumes:
        - name: {{ template "aas-discovery.fullname" $ }}-config
          configMap:
            name: {{ template "aas-discovery.fullname" $ }}-config
        - name: {{ template "aas-discovery.fullname" $ }}-rbac-rules
          configMap:
            name: {{ template "aas-discovery.fullname" $ }}-rbac-rules
{{ end -}}