{{- if and .Values.ingress.enabled .Values.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "aas-discovery.labels" . | nindent 4 }}
  name: {{ include "aas-discovery.fullname" . }}
  annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ include "aas-discovery.fullname" . }}-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        # rewriteTarget: /$1
        pathType: Prefix
        backend:
          service:
            name: {{ include "aas-discovery.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{ end -}}