version: "3.9"
services:
##############################################################################
##############################################################################
###
### Do forget to start docker-compose in basyx.parent to get a running mongodb
###
##############################################################################
##############################################################################
  emqx:
    image: emqx/emqx:5.0.25
    ports:
      - 1883:1883
    networks:
      - basyx-java-server-sdk
  aas-env:
    image: basyx.aasenvironment.component
    volumes:
      - ./aas-env.properties:/application/application.properties
      #- ./aas-env.properties:/usr/share/config/application.properties
    ports:
      - 8081:8081
  aas-repo:
    image: basyx.aasrepository.component
    volumes:
      - ./aas-repo.properties:/application/application.properties
      #- ./aas-repo.properties:/usr/share/config/application.properties
    ports:
      - 8082:8082
