basyx:
  backend: InMemory
  submodelservice:
    submodel:
      file: 
    feature:
      operation:
        dispatcher:
          # enabled by default
          enabled: true
          defaultMapping: org.eclipse.digitaltwin.basyx.submodelservice.feature.operationdispatching.java.DefaultInvokableOperation
          mappings: {}
          java:
            sources:
            classes: classes
            additionalClasspath: []