name: Test Examples

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/CODE_OF_CONDUCT.md'
      - '.github/CODING_CONVENTIONS.md'
      - '.github/CONTRIBUTING.md'
      - '.github/dependabot.yml'
      - '.github/pull_request_template.md'
      - '.github/SECURITY.md'
      - 'docs/**'
      - 'README.md'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
      - 'NOTICE'

jobs:
  test-basyx-client:
    runs-on: ubuntu-latest
    name: Test BaSyx Client Example
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Start BaSyx Client Example
        run: docker compose -f examples/BaSyxClient/docker-compose.yml up -d

      - name: Stop BaSyx Client Example
        run: docker compose -f examples/BaSyxClient/docker-compose.yml down

  test-basyx-databridge:
    runs-on: ubuntu-latest
    name: Test BaSyx DataBridge Example
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Start BaSyx DataBridge Example
        run: docker compose -f examples/BaSyxDatabridge/docker-compose.yml up -d

      - name: Stop BaSyx DataBridge Example
        run: docker compose -f examples/BaSyxDatabridge/docker-compose.yml down

  test-basyx-dynamic-rbac:
    runs-on: ubuntu-latest
    name: Test BaSyx Dynamic RBAC Example
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Start BaSyx Dynamic RBAC Example
        run: docker compose -f examples/BaSyxDynamicRBAC/docker-compose.yaml up -d

      - name: Stop BaSyx Dynamic RBAC Example
        run: docker compose -f examples/BaSyxDynamicRBAC/docker-compose.yaml down

  test-basyx-kafka:
    runs-on: ubuntu-latest
    name: Test BaSyx Kafka Example
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Start BaSyx Kafka Example
        run: docker compose -f examples/BaSyxKafka/docker-compose.yaml up -d

      - name: Stop BaSyx Kafka Example
        run: docker compose -f examples/BaSyxKafka/docker-compose.yaml down

  test-basyx-minimal:
    runs-on: ubuntu-latest
    name: Test BaSyx Minimal Example
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Start BaSyx Minimal Example
        run: docker compose -f examples/BaSyxMinimal/docker-compose.yml up -d

      - name: Stop BaSyx Minimal Example
        run: docker compose -f examples/BaSyxMinimal/docker-compose.yml down

  test-basyx-reverse-proxy:
    runs-on: ubuntu-latest
    name: Test BaSyx Reverse Proxy Example
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Start BaSyx Reverse Proxy Example
        run: docker compose -f examples/BaSyxReverseProxy/docker-compose.yml up -d

      - name: Stop BaSyx Reverse Proxy Example
        run: docker compose -f examples/BaSyxReverseProxy/docker-compose.yml down

  test-basyx-operation-delegation:
    runs-on: ubuntu-latest
    name: Test BaSyx Operation Delegation Example
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Start BaSyx Operation Delegation Example
        run: docker compose -f examples/BaSyxOperationDelegation/docker-compose.yml up -d

      - name: Stop BaSyx Operation Delegation Example
        run: docker compose -f examples/BaSyxOperationDelegation/docker-compose.yml down

  test-basyx-secured:
    runs-on: ubuntu-latest
    name: Test BaSyx Secured Example
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Start BaSyx Secured Example
        run: docker compose -f examples/BaSyxSecured/docker-compose.yaml up -d

      - name: Stop BaSyx Secured Example
        run: docker compose -f examples/BaSyxSecured/docker-compose.yaml down

  test-basyx-node-red:
    runs-on: ubuntu-latest
    name: Test BaSyx Node-RED Example
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Start BaSyx Node-RED Example
        run: docker compose -f examples/BaSyxNodeRED/docker-compose.yml up -d

      - name: Stop BaSyx Node-RED Example
        run: docker compose -f examples/BaSyxNodeRED/docker-compose.yml down

  test-basyx-query-language:
    runs-on: ubuntu-latest
    name: Test BaSyx Query Language Example
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Start BaSyx Query Language Example
        run: docker compose -f examples/BaSyxQueryLanguage/docker-compose.yml up -d

      - name: Stop BaSyx Query Language Example
        run: docker compose -f examples/BaSyxQueryLanguage/docker-compose.yml down

  test-basyx-cad:
    runs-on: ubuntu-latest
    name: Test BaSyx CAD file Example
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Start BaSyx CAD file Example
        run: docker compose -f examples/BaSyxCADFiles/docker-compose.yml up -d

      - name: Stop BaSyx CAD file Example
        run: docker compose -f examples/BaSyxCADFiles/docker-compose.yml down
